env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  import/prefer-default-export: 0
  import/extensions: 0
  import/no-unresolved: 0
  no-use-before-define: 0
  implicit-arrow-linebreak: 0
  no-unused-vars: 0
  react/prop-types: 0
  react/jsx-props-no-spreading: 0
  react/jsx-filename-extension:
    - 'error'
    - extensions:
        - '.jsx'
        - '.tsx'
  '@typescript-eslint/no-use-before-define':
    - error
  '@typescript-eslint/no-unused-vars':
    - error
